matrix:
  include:
    - language: cpp
      script:
        - cd cpp
        - mkdir -p build
        - cd build
        - cmake ..
        - make
        - ./c_example
        - ./cpp_example
        - ./unit_tests
        - ./benchmark_phevaluator
    - language: python
      python: 3.7
      before_install:
        - cd python
      install:
        - pip install -r requirements.txt
      script:
        - cd phevaluator
        - python -m unittest tests.test_evaluator
